# Generated by Django 4.0.4 on 2022-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
