# Generated by Django 4.0.4 on 2022-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_school_region_id_alter_book_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='book',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='user',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('', '')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=255),
        ),
    ]
