# Generated by Django 4.0.4 on 2022-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_book_author_alter_bookdata_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
