# Generated by Django 4.0.4 on 2022-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Id',
            new_name='ID',
        ),
    ]
