# Generated by Django 4.0.4 on 2022-05-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_id_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='user',
            new_name='email',
        ),
    ]
