# Generated by Django 4.0.4 on 2022-05-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_user_bookdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
